### ISSUE TITLE
Proxying video texture for canvas working with demo but canvas tainted with my install

### ISSUE THREAD

**Issue by jarhed** [Rob--W/cors-anywhere#289] opened 2020-10-22 14:23 UTC
I have a little three js app that uses a remotely-hosted mp4 rendered on a canvas as a texture. When using cors-anywhere.herokuapp.com/* everything works fine but when using my own installation, the canvas is tainted, indicating some misconfiguration on my part but I've got no idea what I'm doing wrong.

Any ideas?

**Comment by Rob--W** [comment] 2020-10-22 23:33
There are not enough details here to tell what's wrong. One thing that could cause the issue that you're describing is when the CORS Anywhere instance and your app are using the same origin. By default, same-origin requests are not proxied.

**Comment by jarhed** [comment] 2020-10-23 09:19
They are different URLs, linked as follows so I can't add headers unfortunately.

`
<video>
<source src="https://my-instance.herokuapp.com/https://link-to-mp4.com/video.mp4">
</video>
`
I forked your repo and launched a Heroku instance with it. Have I forgotten to configure something?

**Comment by Rob--W** [comment] 2020-10-23 11:40
Your code is lacking the `crossorigin` attribute, see https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/crossorigin

**Comment by jarhed** [comment] 2020-10-23 14:51
It's got crossorigin="anonymous". The odd thing is that if I use your demo URL, https://cors-anywhere.herokuapp.com/* everything works perfectly. Are there any other details I could send over to you? I've run out of ideas

**Comment by Rob--W** [comment] 2020-10-23 15:01
You could try to debug yourself, with the browser's built-in developer tools (the network tab of it). For CORS, the request and response headers are especially relevant.

For CORS Anywhere, the response body may also be interesting.

**Comment by Rob--W** [comment] 2020-10-23 15:21
... could you be a bit more specific? Browser versions, what you've done to set up the proxy, etc. So far you're not offering enough details for me to be able to provide meaningful support.

**Comment by jarhed** [comment] 2020-10-27 00:05
Hey Rob,

Apologies. Set up and problems as follows:

Set up on heroku:

![Screenshot_20201026_233635](https://user-images.githubusercontent.com/461483/97239840-8833a380-17e4-11eb-89a5-7fc74ed6281e.png)

![Screenshot_20201026_233726](https://user-images.githubusercontent.com/461483/97239852-8c5fc100-17e4-11eb-8600-40dd66535f72.png)

![Screenshot_20201026_233740](https://user-images.githubusercontent.com/461483/97239859-8ff34800-17e4-11eb-93d9-d630ac31f39e.png)

**Comment by Rob--W** [comment] 2020-10-27 20:49
Once more, could you provide ALL relevant details? How am I supposed to help if I don't know how you are sending the request, what the expected behavior, the actual behavior/error messages/responses, etc?

**Comment by jarhed** [comment] 2020-10-28 11:28
Here are the outputs from first my proxy, then yours:

![Screenshot_20201028_105813](https://user-images.githubusercontent.com/461483/97429791-d09bb000-190f-11eb-8d89-6495b0bf0357.png)

![Screenshot_20201028_105951](https://user-images.githubusercontent.com/461483/97429808-d4c7cd80-190f-11eb-922d-cdbfcd58fa7d.png)

My proxy:

![Screenshot_20201028_112800](https://user-images.githubusercontent.com/461483/97430349-aeeef880-1910-11eb-9d10-400485f27afd.png)


Yours:

![Screenshot_20201028_112632-1](https://user-images.githubusercontent.com/461483/97430281-91ba2a00-1910-11eb-9ec9-b0101f9614b2.png)



The only difference is changing the URL from https://cors-random.herokuapp.com/* to https://cors-anywhere.herokuapp.com/*

**Comment by Rob--W** [comment] 2020-10-28 17:37
m3u8 requests are blocked in my proxy due to past abuse, where the public demo was used for streaming.

Your issue reports that "it works with the demo but [not] with [your] install", but the screenshots shows the opposite. I'm not even sure if your last comment refers to the same issue as the initial report, but given that the last behavior is expected, and there is not an issue in the CORS Anywhere core, I'm closing this issue.

**Closed by Rob--W** 2020-10-28 17:37 UTC
