### ISSUE TITLE
Is there a way to host this on a custom path using express?

### ISSUE THREAD

**Issue by Explosion-Scratch** [Rob--W/cors-anywhere#339] opened 2021-03-13 14:34 UTC
I have a server running with express, like so:
```js
const express = require("express");
const app = express();
//Routes here
app.listen(3000, () => console.log("Listening"));
```
but I want to add cors-anywhere at a custom path, like this:
```js
const cors_anywhere = require("cors-anywhere");
const express = require("express");
const app = express();

app.get("/cors-anywhere", () => {
    //What do I do here
})

app.listen(3000, () => console.log("Listening"));
```

**Comment by Rob--W** [comment] 2021-03-13 16:39
Duplicate of #81, see https://github.com/Rob--W/cors-anywhere/issues/81#issuecomment-347346760

**Closed by Rob--W** 2021-03-13 16:39 UTC
