### ISSUE TITLE
Cannot upload to Heroku

### ISSUE THREAD

**Issue by BoHellgren** [Rob--W/cors-anywhere#92] opened 2017-11-07 09:38 UTC
I tried to clone cors-anywhere as per the instruction in https://stackoverflow.com/questions/47076743/cors-anywhere-herokuapp-com-not-working:

git clone https://github.com/Rob--W/cors-anywhere.git
cd cors-anywhere/
npm install
heroku create
git push heroku master

The git push fails with these error messages:

remote: -----> Building dependencies
remote:        Installing node modules (package.json)
remote:        /tmp/build_6c6821946edfbc4f2c9a2f6a9cdf2702/.heroku/node/bin/node[222]: ../src/node_zlib.cc:430:static void node::{anonymous}::ZCtx::Init(const
 v8::FunctionCallbackInfo<v8::Value>&): Assertion `args.Length() == 7 && "init(windowBits, level, memLevel, strategy, writeResult, writeCallback," " dictionar
y)"' failed.
remote:        1: node::Abort() [npm]
remote:        2: node::Assert(char const* const (*) [4]) [npm]
remote:        3: 0x1251ea1 [npm]
remote:        4: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) [npm]
remote:        5: 0xb74c3c [npm]
remote:        6: v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*) [npm]
remote:        7: 0x1f098a4042fd
remote: /app/tmp/buildpacks/19862b8792e84bd8421ded4660b92dfd1c41d92e19ac0b38c90301adc8ae3e0bd512fa01998af18fc2f0d31a157e9c82e8fdceba1a05e5d29adb8dc2bfaf08e1/l
ib/dependencies.sh: line 85:   222 Aborted                 npm install --unsafe-perm --userconfig $build_dir/.npmrc 2>&1
remote:
remote: -----> Build failed

I am running git version 2.15.0.windows.1, node v8.9.0, npm v5.5.1

What have I done wrong?

**Comment by BoHellgren** [comment] 2017-11-07 11:10
I could add that the same commands with the Heroku demo app
https://github.com/heroku/node-js-getting-started
works fine.

**Comment by Rob--W** [comment] 2017-11-07 14:02
Are you sure that this issue is specific to my project?
What version of Node and npm is being installed on Heroku? (these may differ from the versions on your local Windows machine.)

**Comment by BoHellgren** [comment] 2017-11-07 15:03
Since everything works with the Heroku sample application, I don't know
where else the problem could be.

Node 9.0.0 and npm 5.5.1 are installed, as you  can see below.

Regards
Bo

remote: Compressing source files... done.
remote: Building source:
remote:
remote: -----> Node.js app detected
remote:
remote: -----> Creating runtime environment
remote:
remote:        NPM_CONFIG_LOGLEVEL=error
remote:        NPM_CONFIG_PRODUCTION=true
remote:        NODE_VERBOSE=false
remote:        NODE_ENV=production
remote:        NODE_MODULES_CACHE=true
remote:
remote: -----> Installing binaries
remote:        engines.node (package.json):  >=0.10.0
remote:        engines.npm (package.json):   >=1.1.0
remote:
remote:        Resolving node version >=0.10.0...
remote:        Downloading and installing node 9.0.0...
remote:        Bootstrapping npm >=1.1.0 (replacing 5.5.1)...
remote:        npm 5.5.1 installed

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2017-11-07 15:02 GMT+01:00 Rob Wu <notifications@github.com>:

**Comment by BoHellgren** [comment] 2017-11-07 18:12
It works if you change to

"engines": {
  "node": "7.0.0"
}

in your package.json

Regards,
Bo

2017-11-07 16:02 GMT+01:00 Bo Hellgren <bo.hellgren@gmail.com>:

**Comment by balerte** [comment] 2017-11-08 04:00
@BoHellgren thanks for that fix. It worked for me after making that change.

**Comment by Rob--W** [comment] 2017-11-11 00:34
Fixed in the latest master version. This issue was caused by the fact that NPM 5.5.1 is incompatible with Node 9.x. I have removed `engines.npm` from package.json, so the default npm is used. I have successfully pushed the current master to the public demo.

**Closed by Rob--W** 2017-11-11 00:34 UTC
