### ISSUE TITLE
Request work by cors-anywhere Herokuapp and doesn't work with my own server

### ISSUE THREAD

**Issue by ayoubcr5** [Rob--W/cors-anywhere#103] opened 2018-02-01 13:27 UTC
i have installed on my own server cors-anywhere and it works with some request but when i put with this one for exemple 
`http://serverip:8080/https://dvr-i-video-foxmp.akamaized.net/dvr/196b53fe-8760-40ca-810d-e31f12e9a960/196b53fe-8760-40ca-810d-e31f12e9a960.ism/Manifest(video,format=m3u8-aapl-v3,audiotrack=audio,filter=hls) `
i get fobbriden and when i put
`https://cors-anywhere.herokuapp.com/https://dvr-i-video-foxmp.akamaized.net/dvr/196b53fe-8760-40ca-810d-e31f12e9a960/196b53fe-8760-40ca-810d-e31f12e9a960.ism/Manifest(video,format=m3u8-aapl-v3,audiotrack=audio,filter=hls) `
it works
where is the problem 
thank you

**Comment by ayoubcr5** [comment] 2018-02-03 03:23
thank you for the answer
i tried it but it doesn't work also
i want use cors anywhere on my own server to avoit limit of request by 
> https://cors-anywhere.herokuapp.com/
because i use it for live streaming and that will be laggy when using
> https://cors-anywhere.herokuapp.com/
i think just missing some parametre in "server.js" that must be added to avoid access fobbriden

**Comment by Rob--W** [comment] 2018-02-04 17:23
Have you checked whether you can request the site from your server at alll (e.g. by SSHing to the server and using `curl` from the command line)? It is possible that your server is blacklisted by the destination server.

(I also assume that you are using the latest version of CORS Anywhere, if not, use it and try again.)

**Comment by ayoubcr5** [comment] 2018-02-06 15:13
yeah exactly i did it and it's not blacklisted by the destination server .
also i'm using the latest version of CORS Anywhere
i think some configuration is found on Cors Anywhere herokuapp and doesn't have it on my own server 
because as i told you request is working on https://cors-anywhere.herokuapp.com/ and doesn't work on my own server
thank you

**Comment by Rob--W** [comment] 2018-02-06 15:37
Is `serverip` in your example the same as your website? If so, add the `X-Requested-With` request header. I guess that the difference may be caused by the fact that the request is not a cross-origin request, so the `Origin` header is not automatically added.

**Comment by ayoubcr5** [comment] 2018-02-06 16:06
Emm i don't now if it's correct because i don't have a good experience with that
this my configuration of "server.js"
`// Listen on a specific host via the HOST environment variable
var host = process.env.HOST || 'vettoristream.com';
// Listen on a specific port via the PORT environment variable
var port = process.env.PORT || 8080;

var cors_proxy = require('cors-anywhere');
var cors = require('cors');
cors_proxy.createServer({
    originWhitelist: [host], // Allow all origins
    requireHeader: ['origin', 'x-requested-with'],
    removeHeaders: ['cookie', 'cookie2']
}).listen(port, host, function() {
    console.log('Running CORS Anywhere on ' + host + ':' + port);
});`
also to understand my problem you can look
this link contain my own server : http://vettoristream.com/g.html : Doesn't work
and this link containt CORS Anywhere herokuapp : http://vettoristream.com/k.html : Works

**Comment by Rob--W** [comment] 2018-02-06 16:36
In your source code, after the `open` call, set the `X-Requested-With` header, so that you have something like:

```javascript
                    open.call(this, method, rewrittenUrl, async, user, pass);
                    this.setRequestHeader('X-Requested-With', 'XMLHttpRequest');
```

**Comment by ayoubcr5** [comment] 2018-02-06 22:41
also didn't work
bro i think heroku added some following request because when i saw in "server.js" i saw for exemple : "because Heroku already adds it." and me i'm using a server with Os ubuntu and not heroku i think this is the problem
anyway thank you bro for helping me

**Comment by Rob--W** [comment] 2018-02-06 22:47
When you look at the Network tab in the browser's devtools, copy the command as cURL and run the command from the command line (with `-vv` appended for extra verbosity), what do you see? Can you paste the cURL command here too?

**Comment by ayoubcr5** [comment] 2018-02-06 22:54
> root@vmi162223:~/node_modules/cors-anywhere# curl -vv https://dvr-i-video-foxmp.                                                                                        akamaized.net/dvr/94d329a3-44ec-40cf-93f9-b280c1ab7a37/94d329a3-44ec-40cf-93f9-b                                                                                        280c1ab7a37.ism/Manifest
> *   Trying 89.27.241.59...
> * TCP_NODELAY set
> * Connected to dvr-i-video-foxmp.akamaized.net (89.27.241.59) port 443 (#0)
> * ALPN, offering h2
> * ALPN, offering http/1.1
> * Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
> * successfully set certificate verify locations:
> *   CAfile: /etc/ssl/certs/ca-certificates.crt
>   CApath: /etc/ssl/certs
> * TLSv1.2 (OUT), TLS header, Certificate Status (22):
> * TLSv1.2 (OUT), TLS handshake, Client hello (1):
> * TLSv1.2 (IN), TLS handshake, Server hello (2):
> * TLSv1.2 (IN), TLS handshake, Certificate (11):
> * TLSv1.2 (IN), TLS handshake, Server key exchange (12):
> * TLSv1.2 (IN), TLS handshake, Server finished (14):
> * TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
> * TLSv1.2 (OUT), TLS change cipher, Client hello (1):
> * TLSv1.2 (OUT), TLS handshake, Finished (20):
> * TLSv1.2 (IN), TLS change cipher, Client hello (1):
> * TLSv1.2 (IN), TLS handshake, Finished (20):
> * SSL connection using TLSv1.2 / ECDHE-ECDSA-AES256-GCM-SHA384
> * ALPN, server accepted to use http/1.1
> * Server certificate:
> *  subject: C=US; ST=Massachusetts; L=Cambridge; O=Akamai Technologies, Inc.; CN                                                                                        =a248.e.akamai.net
> *  start date: Mar  7 00:00:00 2017 GMT
> *  expire date: May  6 23:59:59 2018 GMT
> *  subjectAltName: host "dvr-i-video-foxmp.akamaized.net" matched cert's "*.akam                                                                                        aized.net"
> *  issuer: C=US; O=Symantec Corporation; OU=Symantec Trust Network; CN=Symantec                                                                                         Class 3 ECC 256 bit SSL CA - G2
> *  SSL certificate verify ok.
> > GET /dvr/94d329a3-44ec-40cf-93f9-b280c1ab7a37/94d329a3-44ec-40cf-93f9-b280c1ab                                                                                        7a37.ism/Manifest HTTP/1.1
> > Host: dvr-i-video-foxmp.akamaized.net
> > User-Agent: curl/7.52.1
> > Accept: */*
> >
> < HTTP/1.1 403 Forbidden
> < Server: AkamaiGHost
> < Mime-Version: 1.0
> < Content-Type: text/html
> < Content-Length: 430
> < Expires: Tue, 06 Feb 2018 22:52:16 GMT
> < Cache-Control: max-age=0, no-cache, no-store
> < Pragma: no-cache
> < Date: Tue, 06 Feb 2018 22:52:16 GMT
> < Connection: keep-alive
> < Access-Control-Max-Age: 86400
> < Access-Control-Allow-Credentials: Server,range,hdntl,hdnts
> < Access-Control-Expose-Headers: Server,range,hdntl,hdnts
> < Access-Control-Allow-Headers: origin,range,hdntl,hdnts
> < Access-Control-Allow-Methods: GET,POST,OPTIONS
> < Access-Control-Allow-Origin: *
> <
> <HTML><HEAD>
> <TITLE>Access Denied</TITLE>
> </HEAD><BODY>
> <H1>Access Denied</H1>
> 
> You don't have permission to access "http&#58;&#47;&#47;dvr&#45;i&#45;video&#45;                                                                                        foxmp&#46;akamaized&#46;net&#47;dvr&#47;94d329a3&#45;44ec&#45;40cf&#45;93f9&#45;                                                                                        b280c1ab7a37&#47;94d329a3&#45;44ec&#45;40cf&#45;93f9&#45;b280c1ab7a37&#46;ism&#4                                                                                        7;Manifest" on this server.<P>
> Reference&#32;&#35;18&#46;37f11b59&#46;1517957536&#46;ca0ab60
> </BODY>
> </HTML>
> * Curl_http_done: called premature == 0
> * Connection #0 to host dvr-i-video-foxmp.akamaized.net left intact
> root@vmi162223:~/node_modules/cors-anywhere#
 
i get this answer i get access denied

**Comment by Rob--W** [comment] 2018-02-06 22:59
That was not what I asked, you're showing the direct response (without the request going through CORS Anywhere). However, it shows the culprit: The remote server has rejected the request from your server.

Furthermore, the remote server already returns the appropriate CORS headers, so you do not even need CORS Anywhere.

```
< Access-Control-Max-Age: 86400
< Access-Control-Allow-Credentials: Server,range,hdntl,hdnts
< Access-Control-Expose-Headers: Server,range,hdntl,hdnts
< Access-Control-Allow-Headers: origin,range,hdntl,hdnts
< Access-Control-Allow-Methods: GET,POST,OPTIONS
< Access-Control-Allow-Origin: *
```

I'm closing this issue since it seems that there are no issues with CORS Anywhere.

**Closed by Rob--W** 2018-02-06 22:59 UTC

**Comment by born69confused** [comment] 2021-03-13 14:39
> Hey!
> I'm in a bit of the same situation, heres an alternative that might work https://secret-ocean-49799.herokuapp.com/ a different repo's implementation. Problem for me is that the site i was requesting, put a ban on the ANS (not sure exactly what it is, something to do with a portion of ips that cant access the site)

Thanks this worked for me

**Comment by codyt11** [comment] 2021-05-04 03:19
A way around this issue is to add a proxy to your package.json file with your local server. ex: "proxy": "localhost:3000/api"
