### ISSUE TITLE
Not found because of proxy error: Error: socket hang up

### ISSUE THREAD

**Issue by jromerob** [Rob--W/cors-anywhere#94] opened 2017-11-08 12:35 UTC
I'm trying to get indications of a walk route quering the Cartociudad service. The service url is ok and responds with a JSON with all the indications.

Testing the service URL in my navigator the result is ok but in my Angular app when i try
http.get("http://127.0.0.1:8123/http://www.cartociudad.es/services/api/route?orig=40.44184877149766,-3.5748567877248845&dest=41.36999441400242,2.1469160601647803&locale=es&vehicle=WALK") the result is a 404 NOT FOUND. Response._body is "Not found because of proxy error: Error: socket hang up"

Trying with other proxy the result is OK. Any ideas ?

Thanks.

**Current proxy.js**
var host = process.env.PORT ? '0.0.0.0' : '127.0.0.1';
var port = process.env.PORT || 8123;

var cors_proxy = require('cors-anywhere');
cors_proxy.createServer({
originWhitelist: [], // permite todos los orígenes
requireHeader: [],
removeHeaders: ['cookie', 'cookie2'],
setHeaders : {
"x-powered-by": "CORS Anywhere"
}
}).listen(port, host, function() {
console.log('Ejecutando proxy en ' + host + ':' + port);
});

**System INFO**
| request http://www.cartociudad.es/services/api/route?orig=40.44184877149766,-3.5748567877248845&dest=41.36999441400242,2.1469160601647803&locale=es&vehicle=WALK
| node 6.11.1
| npm 3.10.10
| Operating System Windows 10

**Comment by Rob--W** [comment] 2017-11-08 14:11
> Trying with other proxy the result is OK.

Is this proxy also running on localhost?

**Comment by jromerob** [comment] 2017-11-08 15:03
Yes, the proxy is on localhost (127.0.0.1:8123)

**Comment by Rob--W** [comment] 2017-11-08 16:14
Not CORS Anywhere, the other proxy that is working according to you. I am asking in order to determine whether the issue is specific to CORS Anywhere, or specific to your local setup (e.g. your IP is blocked by that other site, or your firewall has blocked outbound connections).

**Comment by jromerob** [comment] 2017-11-08 17:04
oh, sorry. No the other proxy isn't on localhost

**Comment by Rob--W** [comment] 2017-11-08 17:24
When you use another program to send the request to the destination, with the same request headers (e.g. curl), does the request succeed?

**Comment by jromerob** [comment] 2017-11-08 17:35
Im not working now tomorrow Will test with CURL. Thanks a lot

**Comment by jromerob** [comment] 2017-11-09 09:37
More info: 

curl -v "127.0.0.1:8123/http://www.cartociudad.es/services/api/route?orig=43.1514858477619,-4.0472363927932&dest=40.44184877149766,-3.5748567877248845&locale=es&vehicle=WALK"                                                              
STATE: INIT => CONNECT handle 0x20081ad8; line 1407 (connection #-5000)                                                                                                                                                                     
Added connection 0. The cache now contains 1 members                                                                                                                                                                                        
  Trying 127.0.0.1...                                                                                                                                                                                                                       
TCP_NODELAY set                                                                                                                                                                                                                             
STATE: CONNECT => WAITCONNECT handle 0x20081ad8; line 1460 (connection #0)                                                                                                                                                                  
Connected to 127.0.0.1 (127.0.0.1) port 8123 (#0)                                                                                                                                                                                           
STATE: WAITCONNECT => SENDPROTOCONNECT handle 0x20081ad8; line 1567 (connection #0)                                                                                                                                                         
Marked for [keep alive]: HTTP default                                                                                                                                                                                                       
STATE: SENDPROTOCONNECT => DO handle 0x20081ad8; line 1585 (connection #0)                                                                                                                                                                  
GET /http://www.cartociudad.es/services/api/route?orig=43.1514858477619,-4.0472363927932&dest=40.44184877149766,-3.5748567877248845&locale=es&vehicle=WALK HTTP/1.1                                                                         
Host: 127.0.0.1:8123                                                                                                                                                                                                                        
User-Agent: curl/7.51.0                                                                                                                                                                                                                     
Accept: */*                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                            
STATE: DO => DO_DONE handle 0x20081ad8; line 1664 (connection #0)                                                                                                                                                                           
STATE: DO_DONE => WAITPERFORM handle 0x20081ad8; line 1791 (connection #0)                                                                                                                                                                  
STATE: WAITPERFORM => PERFORM handle 0x20081ad8; line 1801 (connection #0)                                                                                                                                                                  
HTTP 1.1 or later with persistent connection, pipelining supported                                                                                                                                                                          
HTTP/1.1 200 OK                                                                                                                                                                                                                             
x-request-url: http://www.cartociudad.es/services/api/route?orig=43.1514858477619,-4.0472363927932&dest=40.44184877149766,-3.5748567877248845&locale=es&vehicle=WALK                                                                        
Server Apache-Coyote/1.1 is not blacklisted                                                                                                                                                                                                 
server: Apache-Coyote/1.1                                                                                                                                                                                                                   
content-type: application/json                                                                                                                                                                                                              
transfer-encoding: chunked                                                                                                                                                                                                                  
date: Thu, 09 Nov 2017 09:35:47 GMT                                                                                                                                                                                                         
Marked for [closure]: Connection: close used                                                                                                                                                                                                
connection: close                                                                                                                                                                                                                           
x-final-url: http://www.cartociudad.es/services/api/route?orig=43.1514858477619,-4.0472363927932&dest=40.44184877149766,-3.5748567877248845&locale=es&vehicle=WALK                                                                          
access-control-allow-origin: *                                                                                                                                                                                                              
access-control-expose-headers: server,content-type,transfer-encoding,date,connection,x-final-url,access-control-allow-origin                                                                                                                
                                                                                                                                                                                                                                            
bbox":["-4.153689089872445","40.44187308607131","-3.5741682031937287","43.152457508872246"],"distance":"353022.13238046836","found":"true","from":"43.1514858477619,-4.0472363927932","geom":"yekfGpcuWRm@f@qATo@Ja@n@gAPaACcBn@MfCu@VKRUb@_
e@tC_@`@Gf@KFAA]ZA~DGZCTKpDsBzA}@`K_GbDiBl@YVIv@S\\OLGLWVQHINERCT@bAL`ATl@AvCV`@C|@IdA@hAT`@TX`@Rh@Ll@DjAHj@LJl@h@NPJEPMVSBPLhAL`AH^JZVz@LZLZr@hA|@bAp@l@r@h@~@f@|B|@zDv@dARj@Hd@BF@~@X`Ab@fB~@d@\\x@r@dApALT\\p@JVPVJVLTL^JVNZLTLVZn@PT^j@P
TNVp@`ANRNVZd@T\\j@fAJVLXf@lANVZp@HXj@fAHPBDd@f@b@b@f@\\RNTJRJz@f@`C~@pAr@x@l@hAfARPPTNT`@f@NZPTJT`@f@lAtBp@rANVJNPRJLNFJH`E`BVLVDTD\\DVHTDj@T~@Xn@?xAOf@Wh@]dAoA`@e@ROPSd@a@LSlA}@bAWj@AbAN~@^`@JV?`AS`AYROPSTq@B[A_@?_@A]?_@@_@J{@Tu@L[Zm@
g@ROTIbAQj@?l@Bj@Lj@PRLTHfBnA|@d@TBV?`AWj@IV?TDTHb@`@t@x@RNj@Vh@VRPB@NLPRB@r@p@h@VTHvAb@f@ZPR^j@NVJXTt@LZJV`@j@PFzA^RHTNj@NTHj@VRFj@T`AZRLTJRNRHRJvAj@RLTJpAp@RRb@d@LVJZXn@NV\\p@NRPT^l@n@`ANVNV^j@n@fAJVHZD\\@^H\\JVNTRNTLTJ|@f@THRFn@@bAKl
TIRKTMz@g@~@e@tCqATI`@CH?TBd@NdAb@RLv@v@`AzAJJxDpD\\Vh@PfCLXFTHl@d@b@n@Zz@H`@Db@XtBDPDPFLTXXPZBn@Eh@?b@H`@ZZb@Pj@Jp@@ZCZ@ZDZHXJVNRPLPHTBT?z@Ud@Eh@@d@Hv@b@hC~C\\VTHTB~BAb@Bj@Pp@`@lAnB`AtAVTZJZARGbBmAREPCZA`AFxBr@h@HbC?`AMR@RFRJNNVb@Rt@Xr
ApAVVRHRB\\EhBg@rAM^O\\[dBwBXWd@ErADt@NTHpAlA~@\\NLB@bCbEzAhCnAvBrAzCX`@VTXLt@JdBH@@dGv@hANfBBnDKb@BlBHjAPx@\\fBpAD@B@FFXLx@RfBNt@Xr@j@TXhA|Ax@v@n@b@j@XJBxAb@fAJl@?dCUj@IjAAl@JdBz@^TLDbAR`ACpCi@l@AXHd@Jf@Vd@`@hBvCZ`@p@h@NFRHb@LpBJdANTJD
Bd@b@NTHLP`@Rx@FZTxEV~AVr@N\\v@`AZRNJLDr@^zJhELDj@TZJF@`@JB?hAHp@An@Gl@Qz@a@lCsAlAg@j@OBADAt@QfBU~AA`@BhBP|C~@fCv@f@Hf@BF?J@x@CdAYfDqA|A[tBObB?hAN|Ah@h@`@t@z@l@jATv@|@dF`@jAh@|@t@p@^P`@J`@B`@CnDk@z@GnAC~@BPAl@LbAR~CdAhB^vANpIVtCLp@JfAX|
@z@h@fBfBdAv@TLpBb@^Jh@\\VVTZ|BxDvDpGXn@Nb@RlAjDt\\LbABVHp@LdA`@bBnAjDJZ\\jAX~A\\rCTjATl@|A~CV~@Hj@FbABl@MhI?ZK~G?vBHvAPpAPr@?@@FDR^hAd@fAj@x@j@p@hAz@pAf@v@NpEN`AHjARjAb@fAp@`A~@|@rA`AvAj@x@n@t@d@^JFDDx@^~@T|@DvAAhB?nBAbABx@@T@L?bB\\D@B
BhAl@^\\HJFHh@p@`@x@LRVt@dBxHFRBH\\z@Vh@t@hA~@~@dAp@b@TfFxAzAp@pA`A~A|AZd@f@p@z@bBn@dBZv@f@|@l@z@h@p@h@d@bAx@JF@@RL`B~@z@b@VLdAb@nDbBhCvAlAl@D@XNtAb@zBl@z@NrCb@pCNpCDPArDIrBa@~@[fBy@JEtCuBJGd@_@D?x@e@`@Qt@UnA]x@QXCZC`AAbABz@H~@N~@PhBj@X
@Nx@Zr@^bCtAXP~@t@vAlAVTZZ`BrAvBbBhErDz@p@dBxA|DdDl@f@ZVfGbFfA`AvBlBbCfBv@p@dAbATRb@j@\\h@RXVb@DH|AdC`@|@x@`BJVPZL\\x@nBJ\\Rh@d@vAN^Pj@`@vAPt@J`@XnAR~@FVNn@v@jDVbADP@HH^b@hBV~@JXb@tAl@|A^t@JXr@pAt@hAXh@bAxAHH\\d@jAdBh@~@b@r@Xf@T`@Vf@|@f
ApB^~@Zv@JXJ^HP\\hAN`@HT@@FP~AlFn@fB`@hAJ^Vx@f@lA^x@b@l@JL^`@PJRPf@ZLDFB`@NPBv@HR@V?\\BrA?XCj@ATARAP?h@EZCv@Gn@I^ElAQPEf@K`ASVCzAa@bGcC~BmAbCsAxBuAjBeBtAcBvBaCpByBjAoANQfCwCtBkBpBeBtBuB|BmAlCa@z@FZHTHlA\\bCpApCx@bAF`DEl@CRARCZEf@KZK|@]j

**Comment by jromerob** [comment] 2017-11-09 09:51
Hi i think i found the problem:

I'm loading the app on localhost and the proxy on 127.0.0.1, in this case fails the request
![image](https://user-images.githubusercontent.com/11867464/32599048-a3985ee4-c53b-11e7-9ef1-adadc9f43c56.png)

if load the app over 127.0.0.1 the request works !!
![image](https://user-images.githubusercontent.com/11867464/32599080-b72136de-c53b-11e7-809f-c1b5301db355.png)

**Comment by jromerob** [comment] 2017-11-09 09:54
More info: Changing my configuration to use localhost in request an proxy.js to run CORS Anywhere on localhost (not 127.0.0.1 ) didn´t work:
![image](https://user-images.githubusercontent.com/11867464/32599281-5e5e4c66-c53c-11e7-84f8-5db6b5491320.png)

**Comment by Rob--W** [comment] 2017-11-11 01:24
Is `localhost` resolving to `127.0.0.1` ?

**Comment by jromerob** [comment] 2017-11-11 08:15
Yes

**Comment by Rob--W** [comment] 2017-11-11 09:58
> Curl works right:

Can you use exactly the same `curl` command as the browser (in the devtools you can right-click on a request row and click to copy as a curl command). Then repeatedly issue the request and remove headers at each step until you found which request header results in a difference of how a request is handled.

**Closed** 2018-04-14 09:45 UTC
